web/router.ex
defmodule KickerWeb.Router do
  use KickerWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :minimal_layout do
    plug :put_layout, {KickerWeb.LayoutView, :minimal}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", KickerWeb do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [ :new, :create ], singleton: true
    get "/logout", SessionController, :delete

    get "/", DashboardController, :index
    get "/live", DashboardController, :live
    post "/start", DashboardController, :start
    resources "/players", PlayerController
    get "/profile", PlayerController, :profile
    resources "/matches", MatchController#, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  scope "/api", KickerWeb.API do
    pipe_through :api

    resources "/tables", TableController, except: [:new, :edit]
    resources "/players", PlayerController, except: [:new, :edit]
    resources "/matches", MatchController, only: [:index, :show]
    resources "/rulesets", RulesetController, except: [:new, :edit]
  end
end

web/views/layout_view.ex
defmodule KickerWeb.LayoutView do
  use KickerWeb.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Enrico Mischorr">

    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">

    <title>KickerWeb</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <header class="header">
      <nav class="navigation container" role="navigation">
        <ul class="left">
          <li class="active"><a href="/">Dashboard</a></li>
          <li><a href="/live">Live</a></li>
          <!-- <li><a href="/tables">Tables</a></li> -->
          <li><a href="/players">Players</a></li>
          <li><a href="/matches">Matches</a></li>
          <!-- <li><a href="/rules">Rules</a></li> -->
        </ul>
        <ul class="right">
          <%= if logged_in?(@conn) do %>
          <li><%= link current_player(@conn).forename, to: player_path(@conn, :profile) %></li>
          <% else %>
          <li><a href="<%= session_path @conn, :new %>">Login</a></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <main class="main container" role="main">
      <%
      info = get_flash(@conn, :info)
      error = get_flash(@conn, :error)
      %>
      <%= if info do %>
        <p class="alert alert-info" role="alert"><%= info %></p>
      <% end %>
      <%= if error do %>
        <p class="alert alert-danger" role="alert"><%= error %></p>
      <% end %>

      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer>
      <div class="container">
        <span class="right">&copy; Enrico Mischorr</span>
      </div>
    </footer>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/minimal.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Enrico Mischorr">

    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">

    <title>KickerWeb</title>
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%
      info = get_flash(@conn, :info)
      error = get_flash(@conn, :error)
      %>
      <%= if info do %>
        <p class="alert alert-info" role="alert"><%= info %></p>
      <% end %>
      <%= if error do %>
        <p class="alert alert-danger" role="alert"><%= error %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>